---
id: mnemo
name: Mnemo
full: Notes application
description: >-
  The Mnemo Note Manager is the Horde notes/memos application. It allows users
  to keep web-based notes and freeform text. Notes may be shared with other
  users via shared notepads. It requires the Horde Application Framework and an
  SQL database or Kolab server for backend storage.
list: horde
type: application
homepage: https://www.horde.org/apps/mnemo
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 5.0.0alpha1
  api: 5.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: ASL
  uri: http://www.horde.org/licenses/apache
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/content: ^2.0.5
      pear.horde.org/horde: ^5
      pear.horde.org/Horde_Auth: ^2
      pear.horde.org/Horde_Core: ^2.31
      pear.horde.org/Horde_Data: ^2
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Form: ^2
      pear.horde.org/Horde_Group: ^2
      pear.horde.org/Horde_History: ^2.1
      pear.horde.org/Horde_Icalendar: ^2
      pear.horde.org/Horde_Injector: ^2
      pear.horde.org/Horde_Perms: ^2
      pear.horde.org/Horde_Prefs: ^2
      pear.horde.org/Horde_Share: ^2.2
      pear.horde.org/Horde_Support: ^2
      pear.horde.org/Horde_Text_Filter: ^2
      pear.horde.org/Horde_Util: ^2
    ext:
      gettext: '*'
  optional:
    pear:
      pear.horde.org/Horde_ActiveSync: ^2.4
      pear.horde.org/Horde_Backup: ^1
      pear.horde.org/Horde_Cli: ^2
      pear.horde.org/Horde_Crypt: ^2
      pear.horde.org/Horde_Db: ^2.1
      pear.horde.org/Horde_Pdf: ^2
      pear.horde.org/Horde_Test: ^2
